name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libgirepository1.0-dev gir1.2-nautilus-4.0 gir1.2-girepository-2.0-dev python3-gi pkg-config python3-nautilus libnotify-bin pdfunite pandoc unoconv

      - name: Install Python dependencies
        run: |
          pip install sphinx sphinx-rtd-theme PyGObject

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html