name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Update and install system dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y \
            build-essential \
            software-properties-common \
            libgirepository1.0-dev \
            gir1.2-girepository-2.0 \
            python3-gi \
            pkg-config \
            libcairo2-dev \
            gobject-introspection \
            libglib2.0-dev \
            libffi-dev \
            gir1.2-nautilus-3.0

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme PyGObject==3.42.1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install gh-pages
        run: |
          npm install -g gh-pages

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        run: |
          gh-pages -d docs/_build/html
          gh repo set-default
          gh pages publish docs/_build/html
